generic-service:
  nameOverride: hmpps-manage-users-temp-rewrite
  productId: 'DPS017'

# the IRSA service account name for accessing AWS resources
#  serviceAccountName: "hmpps-manage-users-temp-rewrite"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-manage-users-temp-rewrite
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-manage-users-temp-rewrite-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'DPS017' # Your audit service name

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
#   using hmpps-manage-users secrets as code will be copied into repo once complete
    hmpps-manage-users:
      AUTH_CODE_CLIENT_ID: "API_CLIENT_ID"
      AUTH_CODE_CLIENT_SECRET: "API_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
    hmpps-manage-users-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    hmpps-redis:
      REDIS_HOST: "REDIS_HOST"
      REDIS_PASSWORD: "REDIS_PASSWORD"
    hmpps-manage-users-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-manage-users-temp-rewrite
