---
# Per environment values which override defaults in hmpps-manage-users-temp-rewrite/values.yaml

generic-service:
  ingress:
    host: manage-users-temp-rewrite.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://manage-users-temp-rewrite.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EXAMPLE_API_URL: 'https://template-kotlin.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps_tech
